namespace: dev-databases

storageClass: standard-ssd

postgres:
  storage: 20Gi

redis:
  enabled: true

  resources:
    requests:
      cpu: "250m"
      memory: "1Gi"
    limits:
      cpu: "500m"
      memory: "2Gi"

  config:
    maxmemory: "2gb"
    maxmemory-policy: "allkeys-lru"

cosmos:
  storage: 20Gi

tcpPorts:
  postgres: 5432
  redis: 6379
  cosmos: 8081

ingress:
  enabled: true
  className: nginx
  hosts:
    postgres: postgres-dev.ielsportal.com
    redis: redis-dev.ielsportal.com
    cosmos: cosmos-dev.ielsportal.com
  tls:
    enabled: true
    secretName: wildcard-secret
